### ISSUE TITLE
Crashed when enabling the trade added

### ISSUE THREAD

**Issue by linzexin022** [HyperPigeon/Better-Wandering-Trader#2]
Hi there, I met crashes when enabled the trades I've added. Here's my config:

`{ 
	"trades": { 
		"enable_user_added_traded": true
	},
	"invisibleTradeFactory": { 
		"number_of_trades": 1,
		"trades_to_choose": 2,
		"array": [ 
			{ 
				"identifier": "minecraft:enchanted_golden_apple",
				"price": 36,
				"count": 1,
				"maxUses": 1,
				"experience": 1
			},
			{ 
				"identifier": "origins:orb_of_origin",
				"price": 64,
				"count": 1,
				"maxUses": 8,
				"experience": 1
			}
		]
	},
	"example": { 
		"identifier": "minecraft:end_crystal",
		"price": 0,
		"count": 0,
		"maxUses": 0,
		"experience": 0
	}
}`

However, the server crashed and showed these log:

`[main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'sandwichable'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
	at net.minecraft.server.Main.main(Main.java:125) [intermediary-server.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at io.github.foundationgames.sandwichable.villager.SandwichMakerProfession.init(SandwichMakerProfession.java:57) ~[sandwichable-1.1.1-snapshot__1.16-pre2.jar:?]
	at io.github.foundationgames.sandwichable.Sandwichable.onInitialize(Sandwichable.java:56) ~[sandwichable-1.1.1-snapshot__1.16-pre2.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at net.minecraft.class_3853.<clinit>(class_3853.java:526) ~[intermediary-server.jar:?]
	at io.github.foundationgames.sandwichable.villager.SandwichMakerProfession.init(SandwichMakerProfession.java:57) ~[sandwichable-1.1.1-snapshot__1.16-pre2.jar:?]
	at io.github.foundationgames.sandwichable.Sandwichable.onInitialize(Sandwichable.java:56) ~[sandwichable-1.1.1-snapshot__1.16-pre2.jar:?]
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
	... 17 more`

I guess it's caused by the sandwich traders in Sandwichable, don't know if you can fix it?

**Comment by HyperPigeon** [comment]
Thank you for bringing this issue to my notice. I'll try to resolve this issue in the next update of the mod.

**Comment by HyperPigeon** [comment]
After examining the issue, I think  _that the fault may lie with Sandwichables_. I'll try to do more testing to see if it's a fault on my end, but if it's a problem with Sandwichables I'll try to get into contact with the mod author.

**Comment by scottwilson0308** [comment]
Hey, just popping in to pass along what I've learned. I had a massive headache of a time troubleshooting, so I hope it will help you somehow.

Very similar issue (with my crash blaming Charm) though all I did in your config was set custom trades to TRUE, I didn't actually change the config any more than that.

I've recently started using MultiMC 5 Version 0.6.12-1530, running Minecraft 1.16.5 and Fabric 0.11.3...
I created a new instance with only Fabric API, BWT and Charm. I let them create their own config files, changed your custom trades config to TRUE and it crashed yet again.

[latest.log](https://github.com/HyperPigeon/Better-Wandering-Trader/files/6480624/latest.log)
[crash-2021-05-14_14.14.45-client.txt](https://github.com/HyperPigeon/Better-Wandering-Trader/files/6480625/crash-2021-05-14_14.14.45-client.txt)


Hopefully my pain and suffering will help you all in some way.
Cheers!

**Comment by red2blue** [comment]
@HyperPigeon any word on this??????
