### ISSUE TITLE
Server crashes when I try to use this mod.

### ISSUE THREAD

**Issue by r4ndomlog** [HyperPigeon/Better-Wandering-Trader#9]
When I add this mod to my server the server crashes. The only other mods I have on my server is Lithium, Phosphor and StyledPlayerList this is the console when I try to run the server.

[06.03 09:37:50] [Multicraft] Received start command
[06.03 09:37:50] [Multicraft] Loading server properties
[06.03 09:37:50] [Multicraft] Starting server!
[06.03 09:37:50] [Multicraft] Loaded config for "Special: customjava17.jar"
[06.03 09:37:51] [Multicraft] Updating eula.txt file
[06.03 09:37:51] [Server] WARNING Using incubator modules: jdk.incubator.vector
[06.03 09:37:51] [Server] Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[06.03 09:37:51] [Server] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.2
[06.03 09:37:52] [Server] [Log4jPatch] [INFO] Patching org/apache/logging/log4j/core/lookup/JndiLookup
[06.03 09:37:52] [Server] [Log4jPatch] [INFO] Patching org/apache/logging/log4j/core/pattern/MessagePatternConverter
[06.03 09:37:52] [Server] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.2
[06.03 09:37:53] [Server] [main/WARN]: Mod resolution failed
[06.03 09:37:53] [Server] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE better_wandering_trader 1.8.0 {depends fabric @ [*]}, ROOT_FORCELOAD_SINGLE better_wandering_trader 1.8.0]
[06.03 09:37:53] [Server] [main/INFO]: Reason: [HARD_DEP better_wandering_trader 1.8.0 {depends fabric @ [*]}]
[06.03 09:37:53] [Server] [main/INFO]: Fix: add [add:fabric 1 ([(-∞,∞)])], remove [], replace []
[06.03 09:37:53] [Server] [main/ERROR]: Incompatible mod set!
[06.03 09:37:53] [Server] net.fabricmc.loader.impl.FormattedExceptionMod resolution encountered an incompatible mod set!
[06.03 09:37:53] [Server] A potential solution has been determined:
[06.03 09:37:53] [Server] 	 - Install fabric, any version.
[06.03 09:37:53] [Server] Unmet dependency listing:
[06.03 09:37:53] [Server] 	 - Mod 'Better Wandering Trader' (better_wandering_trader) 1.8.requires any version of fabric, which is missing!
[06.03 09:37:53] [Server] 	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.13.2.jar:?]
[06.03 09:37:53] [Server] 	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142) ~[fabric-loader-0.13.2.jar:?]
[06.03 09:37:53] [Server] 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71) [fabric-loader-0.13.2.jar:?]
[06.03 09:37:53] [Server] 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.13.2.jar:?]
[06.03 09:37:53] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[06.03 09:37:53] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
[06.03 09:37:53] [Server] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[06.03 09:37:53] [Server] 	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
[06.03 09:37:53] [Server] 	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:66) [fabric-loader-0.13.2.jar:?]
[06.03 09:37:53] [Server] 	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:64) [customjava17.jar:0.10.2]
[06.03 09:37:53] [Multicraft] Server shut down (starting)
[06.03 09:37:53] [Multicraft] Restarting crashed server in 5 seconds
[06.03 09:37:53] [Multicraft] Looks like a crash, check the server console. Return value: 1
[06.03 09:37:53] [Multicraft] Server stopped

**Comment by MeeniMc** [comment]
you need to install the mod `fabric-api` for 1.18.1
